config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	get '/home', to: 'pages#home'
	
	#get '/recipes', to: 'recipes#index'
	#get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
	#to handle the submission of a new recipe, use a form:
	#post '/recipes', to: 'recipes#create'
	#get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
	
	#how to handle the edit_recipe submission:
	#put '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
	
	#Show individual recipes:
	#get 'recipes/:id', to: 'recipes#show', as: 'recipe'
	
	#Delete recipe:
	#delete '/recipes/:id', to: 'recipes#destroy'
	
	resources :recipes do
		member do
			post 'like'
		end
	end
	
	resources :chefs, except: [:new]
	
	get '/register', to: 'chefs#new'
	
#	login -> new session
	get '/login', to: 'logins#new'
	
#	post login -> create session
	post '/login', to: 'logins#create'
	
#	logout -> close session
	get '/logout', to: 'logins#destroy'


end

app/models/chef.rb
class Chef < ActiveRecord::Base
	
	#define association
	has_many :recipes
	has_many :likes
	
	
	#before-save callback; before saving emails, convert them to lowercase
	before_save { self.email = email.downcase }
	
	validates :chefname , presence: true, length: {minimum: 3, maximum: 40}
	# From http://emailregex.com/
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 40},
						uniqueness: { case_sensitive: false },
						format: { with: VALID_EMAIL_REGEX }
	#From api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
	has_secure_password

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
	before_action :set_chef, only: [:edit, :update, :show]
	#this action will be performed before all other actions!
	before_action :require_same_user, only: [:edit, :update]
	
	def index
		@chefs = Chef.paginate(page: params[:page], per_page: 3)
	end
	
	def new
		@chef = Chef.new
	end
	
	#will hand the new action
	def create
#		binding.pry
		@chef = Chef.new(chef_params)
		if @chef.save
			flash[:success] = "Your account has been create successfully"
			#start the session for the user
			session[:chef_id] = @chef.id
			redirect_to recipes_path
		else
			render 'new'
		end
	end
	
	def edit

		#enforce chef can edit only their own recipes
	end
	
	#will handle the the edit action
	def update
#		binding.pry

		if @chef.update(chef_params)
			flash[:success] = "Your profile has been updated successfully"
			redirect_to chef_path(@chef)
		else
			render 'edit'
		end
	end
	
	
	def show

		@recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
	end
	
	private
	def chef_params
		params.require(:chef).permit(:chefname, :email, :password)
	end
	
	def set_chef
			@chef = Chef.find(params[:id])
	end
	
	def require_same_user
		if current_user != @chef
			flash[:danger] = "You can only edit your own profile"
			redirect_to root_path
		end
	end
end

app/views/chefs/_form.html.erb
<!--Pass in @chef as the object-->
<%= render 'shared/errors', object: @chef %>

<div class="row">
	<div class="well col-md-8-offset-2">
		<!--Allow for file upload-->
		<%= form_for @chef do |f| %>
		<%= f.label :chef_name %>
		<%= f.text_field :chefname %>
		
		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>
		
		<!--Ruby boolean; is this a new record, yes or no?-->
		<%= f.submit(@chef.new_record? ? 'Register' : 'Edit Profile', class:"btn btn-md btn-success") %>
		<%end %>
	</div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/title', title: "Edit Your Profile" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/title', title: "All Chefs" %>

<ul class="nav nav-tabs">
	<li>
		<%= link_to "Recipes", recipes_path%>
	</li>
	<li>
	
	<li class="active">
		<%= link_to "Chefs", chefs_path %>
	</li>
</ul>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= will_paginate %>
	</div>
</div>

<% @chefs.each do |chef|%>
	<div class="row">
		<div class="col-md-4 col-md-offset-4 center">
			<%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
			<p><h5>Chef: <%= chef.chefname%></h5></p>
			<hr>
		</div>
</div>
<% end%>

app/views/chefs/new.html.erb
<%= render 'shared/title', title: "Register your account" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/title', title: "Chef " + @chef.chefname%>
	
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @chef, size: 200 %>
		<hr>
	</div>
</div>

<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<h3><em>Recipes:</em></h3>
		<%= will_paginate @recipes %>
	</div>
</div>

<% @recipes.each do |recipe|%>

	<div class="row">
		<div class="col-lg-6 well">
			<h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
			<p><%= recipe.summary %></p>
			<p>
				<span class="quiet">
					<small>Created:<%= time_ago_in_words(recipe.created_at) %> ago,</small>
				</span>
				<span class="quiet">
					<small>Updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small>
				</span>
			</p>

			<!--Display likes -->
			<div class="pull-right">
				<%= link_to like_recipe_path(recipe, like:true), method: :post do%>
				<i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
				<% end %> &nbsp;
				<%= link_to like_recipe_path(recipe, like:false), method: :post do%>
				<i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
				<% end %>
			</div>
		</div>

		<div class="col-md-4">
			<!--Return true if there is a picture, else don't-->
			<%= image_tag(recipe.picture.url, size: "250x150", class:"gravatar") if recipe.picture? %>
		</div>
		
	</div>
<% end %>