config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	get '/home', to: 'pages#home'
	
	#get '/recipes', to: 'recipes#index'
	#get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
	#to handle the submission of a new recipe, use a form:
	#post '/recipes', to: 'recipes#create'
	#get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
	
	#how to handle the edit_recipe submission:
	#put '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
	
	#Show individual recipes:
	#get 'recipes/:id', to: 'recipes#show', as: 'recipe'
	
	#Delete recipe:
	#delete '/recipes/:id', to: 'recipes#destroy'
	
	resources :recipes do
		member do
			post 'like'
		end
	end
	
	resources :chefs, except: [:new]
	
	get '/register', to: 'chefs#new'
	
#	login -> new session
	get '/login', to: 'logins#new'
	
#	post login -> create session
	post '/login', to: 'logins#create'
	
#	logout -> close session
	get '/logout', to: 'logins#destroy'


end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	
	#define association
	belongs_to :chef
	has_many :likes
	
	validates :chef_id, presence: true
	#validate name and enforce the presence is true otherwise, returns false
	validates :name, presence: true, length: {minimum: 5, maximum: 25}
	validates :summary, presence: true, length: {minimum: 5, maximum: 50}
	validates :description, presence: true, length: {minimum: 10, maximum: 5000}

	mount_uploader :picture, PictureUploader
	validate :picture_size
	#what to pickup in ActiveRecord in descending order
	default_scope -> {order(updated_at: :desc)}
	
	def thumbs_up_total
		self.likes.where(like: true).size
	end
	
	def thumbs_down_total
		self.likes.where(like: false).size
	end
	
	private
	def picture_size
		#Ensure the image uploaded on the server side is more than 5Mb
		if picture.size > 5.megabytes
			errors.add(:picture, "Should be less than 5Mb")
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :set_recipe, only: [:edit, :update, :show, :like]
	before_action :require_user, except: [:show, :index] #requires method defined in application_controller...
	before_action :require_same_user, only: [:edit, :update]
	
	#index action 
	def index
		#goes to db, graps all recipes & stores in @recipes object
		#show trending recipes according to likes
		@recipes = Recipe.paginate(page: params[:page], per_page: 5)
		
#		@recipes = Recipe.all.sort_by{ |likes| likes.thumbs_up_total }.reverse
	end
	
	def new
		@recipe = Recipe.new
	end
		
	def create
#		binding.pry
		@recipe = Recipe.new(recipe_params)
		#current_user predefined in before_action ;)
		@recipe.chef = current_user
		
		if @recipe.save
			#send notification
			flash[:success] = "Your recipe was created successfully"
			redirect_to recipes_path
		else
			render :new
		end
	end
	
	def edit
		#How to find a recipe via its id:
		
	end
	
	def update

		if @recipe.update(recipe_params)
			flash[:success] = "Your recipe was updated successfully"
			redirect_to recipe_path(@recipe)
		else
			render :edit
		end
	end
	
	def like
		#	binding.pry
		# like is the key, params[:like] is the value: #chef is hard coded for now!
		like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
		if like.valid?
			flash[:success] = "Your selection was successful"
			redirect_to :back #send the user back 
		else
			flash[:danger] = "You can only like/dislike a recipe once"
			redirect_to :back
		end
	end
	
	def show
		#use gemfile
		#binding.pry
		#search by id

	end
	
	#whitelist methods exclusive to this class
	private
		
	def recipe_params
		params.require(:recipe).permit(:name, :summary, :description, :picture)
	end
	
	def set_recipe
		@recipe = Recipe.find(params[:id])
	end
	
	def require_same_user
		if current_user != @recipe.chef
			flash[:danger] = "You can only edit your own recipes"
			redirect_to recipes_path
		end
	end
	
end

app/views/recipes/_form.html.erb
<!--Pass in @recipe as the object-->
<%= render 'shared/errors', object: @recipe %>

<div class="row">
	<div class="well col-md-8-offset-2">
		<!--Allow for file upload-->
		<%= form_for(@recipe, html: {multipart: true }) do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<%= f.label :summary %>
		<%= f.text_field :summary %>
		
		<%= f.label :description %>
		<%= f.text_area :description, rows:10 %>
		
		<span class="picture">
			<!--Accepting these formats of images:-->
			<%= f.file_field :picture, accept: 'image/png,image/jpg,image/jpeg,image/gif,image/bmp' %>
		</span>
		
		<!--Ruby boolean; is this a new record, yes or no?-->
		<%= f.submit(@recipe.new_record? ? 'Create recipe' : 'Edit recipe', class:"btn btn-md btn-success") %>
		<%end %>
	</div>
</div>

<!--(JQuery)valid if the file upload is less than 5Mb-->
<script type="text/javascript">
	$('#recipe_picture').bind('change', function() {
		size_in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 5)
			alert('Maximum file size is 5Mb. Please choose a smaller file.');
			}
	});
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/title', title: "All Recipes" %>

<ul class="nav nav-tabs">
	<li class="active">
		<%= link_to "Recipes", recipes_path%>
	</li>
	<li>
	
	<li>
		<%= link_to "Chefs", chefs_path %>
	</li>
</ul>

<%= will_paginate %>

<!--Iterate through each one of the recipes-->
<% @recipes.each do |recipe|%>
	<div class="row">
		<div class="col-md-2">
			<section class="chef_info center">
			
				<!--Add gravatar image-->
				<%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef)%>
				<h5>Chef name: <%= recipe.chef.chefname %></h5>	
			</section>
		</div>

		<div class="col-lg-6 well">
			<h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
			<p><%= recipe.summary %></p>
			<p>
				<span class="quiet">
					<small>Created:<%= time_ago_in_words(recipe.created_at) %> ago,</small>
				</span>
				<span class="quiet">
					<small>Updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small>
				</span>
			</p>
			
			<!--Display likes -->
			<div class="pull-right">
				<%= link_to like_recipe_path(recipe, like:true), method: :post do%>
				<i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= recipe.thumbs_up_total %>
				<% end %> &nbsp;
				<%= link_to like_recipe_path(recipe, like:false), method: :post do%>
				<i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= recipe.thumbs_down_total %>
				<% end %>
			</div>
			
		</div>
		
		<div class="col-md-4">
			<!--Return true if there is a picture, else don't-->
			<%= image_tag(recipe.picture.url, size: "250x150", class:"gravatar") if recipe.picture? %>
		</div>

	</div>
<hr>
<% end %>


<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/title', title: "Create New Recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/title', title: @recipe.name %>

<div class="row">
	<div class="col-md-4 pull-right center">
		<!--Show the chef associated with the recipe-->
		<%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
		<p>
			<h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
		</p>
	</div>
	
	<div class="col-md-8">
			<!--Adding authentication here-->
			<% if logged_in? and @recipe.chef == current_user %>
			<%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: "btn btn-default pull-right"%>
		<% end %>
		<h3><%= @recipe.summary %></h3>
		
		<div class="show_recipe">
			<%= image_tag(@recipe.picture.url, class:"gravatar") if @recipe.picture? %>
		</div>
		
		<div class="well">
			<p>
				<strong>Steps:</strong>
			</p>
			<!--Display contents per line-->
			<%= simple_format(@recipe.description) %>
			<!--Display likes -->
			<div class="pull-right">
				<%= link_to like_recipe_path(@recipe, like:true), method: :post do%>
				<i class="glyphicon glyphicon-thumbs-up"></i> &nbsp; <%= @recipe.thumbs_up_total %>
				<% end %> &nbsp;
				<%= link_to like_recipe_path(@recipe, like:false), method: :post do%>
				<i class="glyphicon glyphicon-thumbs-down"></i> &nbsp; <%= @recipe.thumbs_down_total %>
				<% end %>
			</div>
		
		</div>
	</div>
</div>

<h5><%= link_to "Return to Recipes Listing", recipes_path, class: "btn btn-default btn-md" %></h5>