config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	get '/home', to: 'pages#home'
	
	#get '/recipes', to: 'recipes#index'
	#get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
	#to handle the submission of a new recipe, use a form:
	#post '/recipes', to: 'recipes#create'
	#get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
	
	#how to handle the edit_recipe submission:
	#put '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
	
	#Show individual recipes:
	#get 'recipes/:id', to: 'recipes#show', as: 'recipe'
	
	#Delete recipe:
	#delete '/recipes/:id', to: 'recipes#destroy'
	
	resources :recipes do
		member do
			post 'like'
		end
	end
	
	resources :chefs, except: [:new]
	
	get '/register', to: 'chefs#new'
	
#	login -> new session
	get '/login', to: 'logins#new'
	
#	post login -> create session
	post '/login', to: 'logins#create'
	
#	logout -> close session
	get '/logout', to: 'logins#destroy'


end

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>맛있서  Mashiso </h1>
	<h3>Delicious Korean Recipes</h3>
	
	<%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success"%>
</div>

<div class="row">
	<div class="col-lg-4">
		<h3 class="mid-row">Top option</h3>
		<h4 class="left">Something here</h4>
		<p><%= link_to "Browse recipe listings", recipes_path, class:"btn btn-md btn-warning"%></p>
	</div>
	<div class="col-lg-4">
		<h3 class="mid-row">Sign in to your account</h3>
		<h4 class="left">Add/Update your recipes | Create reviews/like-dislike recipes and much much more!</h4>
		<p><%= link_to "Login into your account", "login", class:"btn btn-md btn-warning"%></p>
	</div>
	<div class="col-lg-4">
		<h3 class="mid-row">View Recipes as guest user</h3>
		<h4 class="left">Browse and view recipes as a guest and sign up later</h4>
		<p><%= link_to "Browse recipe listings", "", class:"btn btn-md btn-warning"%></p>
	</div>
</div>