config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
	get '/home', to: 'pages#home'
	
	#get '/recipes', to: 'recipes#index'
	#get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
	#to handle the submission of a new recipe, use a form:
	#post '/recipes', to: 'recipes#create'
	#get '/recipes/:id/edit', to: 'recipes#edit', as: 'edit_recipe'
	
	#how to handle the edit_recipe submission:
	#put '/recipes/:id', to: 'recipes#update', as: 'update_recipe'
	
	#Show individual recipes:
	#get 'recipes/:id', to: 'recipes#show', as: 'recipe'
	
	#Delete recipe:
	#delete '/recipes/:id', to: 'recipes#destroy'
	
	resources :recipes do
		member do
			post 'like'
		end
	end
	
	resources :chefs, except: [:new]
	
	get '/register', to: 'chefs#new'
	
#	login -> new session
	get '/login', to: 'logins#new'
	
#	post login -> create session
	post '/login', to: 'logins#create'
	
#	logout -> close session
	get '/logout', to: 'logins#destroy'


end

app/views/layouts/_footer.html.erb
	<div class="footer">
		<p>&copy; Mashiso 2016</p>
	</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-12">
	
		<% flash.each do |message_type, message|%>
			<div class="alert alert-<%= message_type %>">
				<%= message%>
				<a class="close" data-dismiss="alert">&#215;</a>
			</div>
		<% end %>

		</div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-default nav-bar-fixed-top">
	<div class="container">
		<%= link_to "Mashiso", root_path, id:"logo" %>
				
		<div class="nav_item">
			<%= link_to "About", "/path"%>
		</div>
				
		<% if logged_in? %>

		<!--Display dropdown menu options-->
				<ul class="nav_item">
					<li class="dropdown">
						<%= link_to '#', class:"dropdown-toggle", "data-toggle" => "dropdown" do %>
							<%= current_user.chefname %> <b class="caret"></b>
					<% end %>
						<ul class="dropdown-menu">
							<li><%= link_to "View Profile", chef_path(current_user) %></li>
							<li><%= link_to "Edit Profile", edit_chef_path(current_user) %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to "Logout", logout_path %></li>
						</ul>
					</li>
				</ul>
			<div class="nav_item">
				<%= link_to "Add recipe", new_recipe_path%>
			</div>
		
			<% else %>			

				<div class="nav_item">
				<%= link_to "Log in", login_path %>
			</div>
			
			<% end %>

		<div class="nav_item">
			<%= link_to "View recipes", recipes_path%>
		</div>

	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mashiso</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
<div class="container">
	<%= render 'layouts/messages' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>
</body>
</html>